### ISSUE TITLE
Several pages with reCaptcha

### ISSUE THREAD

**Issue by RoRElessar** [igorkasyanchuk/new_google_recaptcha#1]
I use reCaptcha v3. On the website I have 2 pages with form, that include reCaptcha. When I visit the first page - reCaptcha works fine, but when I visit the second one by clicking the menu link (current location is the first page that contains the form with reCaptcha), recaptcha doesn't work. When I inspect the page, the reCaptcha's token input's value is absent. When I visit a page without the form, and then visit a page with form, reCaptcha works fine, the hidden field's value contains the token.

This is how I include the script on the page:
```
<%= content_for :recaptcha_js do %>
  <%= raw %Q{
        <script src="https://www.google.com/recaptcha/api.js?render=#{ENV['RECAPTCHA_SITE_KEY']}" data-turbolinks-track="reload"></script>
      } %>
<% end %>
```

Any ideas how to make it work? Thanks ahead.

**Comment by igorkasyanchuk** [comment]
I see that you have turbolinks.
does it work when you disable them completely?

**Comment by RoRElessar** [comment]
I tried, but nothing changed

**Comment by igorkasyanchuk** [comment]
@RoRElessar can you please make a PR and add a section with instructions on how to make it work with Turbolinks. It would be very useful.
