### ISSUE TITLE
Too huge requests amount (recaptcha admin console)

### ISSUE THREAD

**Issue by adelnabiullin** [igorkasyanchuk/new_google_recaptcha#10]
Sorry for posting it here, but I cannot find google's support for developers
And may it will be useful for others who use recaptcha v3, too

Question: I integrated the gem and after first day of usage on production I have following:

<img width="1451" alt="Снимок экрана 2019-03-27 в 12 54 21" src="https://user-images.githubusercontent.com/4465325/55066776-81383280-508f-11e9-939a-4778d657f4d4.png">

As you can see there are 4k+ requests in one day, but actually form was submitted only 3 times that day

It's very strange

I have 2 ideas:
1) Google Analytics integrated as well (we use it for several years now), so maybe google just collected (GA) users behavior around the form where I integrated recaptcha and now shows it to me like it was yesterday
2) Recaptha that I integrated into form sends requests to google not only when user submits the form, but it does it permanently with some delay and with high frequency

Could you please explain its behavior please if you know
Thanks in advance

**Comment by igorkasyanchuk** [comment]
maybe you have bots on site?

**Comment by adelnabiullin** [comment]
maybe
I thought that amount of requests should be equal to amount of form submits
but seems like I understand now how recaptcha v3 works, looks like in recaptcha admin panel I see requests sent when someone **visited** the page with form where I integrated recaptcha, **not only** those cases when user **submitted** the form

**Comment by adelnabiullin** [comment]
sorry for wasting your time

**Comment by adelnabiullin** [comment]
> maybe you have bots on site?

I think score would be less than 0.9 if that were bots 😄

**Comment by adelnabiullin** [comment]
Do you know if there is some way to make the only form with recaptcha (but not the whole page where this form placed) affect analytics in the admin panel?

**Comment by igorkasyanchuk** [comment]
I've score 0.5 and no spam. Also try to include js only on page where you have form. Not in the main layout with content_for and yield

**Comment by adelnabiullin** [comment]
Js is already only on a page with the form
But this form is in a modal appearing on click
And this page with form has huge traffic

I thought about trying to wrap that modal into iframe, but I think it most likely won't help
So finally the only solution that I see is to move the form to separate page, but I will not :)

**Comment by igorkasyanchuk** [comment]
Just curious but maybe it is to load this in Ajax. Right after form is loaded in modal window

**Comment by adelnabiullin** [comment]
Good suggestion, thank you :)
In the end I decided to leave it as it is to give more time for google to analyze people behavior

P.S. I'm planning to monkey-patch your gem or fork it
I want to store humanity score in db because it can be useful, for example to be able to remove some untrusted reviews later (e.g. if minimum score was 0.5 and someone found a way to pass recaptcha with 0.5) or maybe because I'm just paranoid
If you want this feature I can do a pull request ;)
