### ISSUE TITLE
Did change params "new_google_recaptcha_token" -> "new_recaptcha_token" ?

### ISSUE THREAD

**Issue by cyborgninja** [igorkasyanchuk/new_google_recaptcha#27]
My website cannot work recaptcha v3 ( I found 2021/08/13 MAYBE 17:00 JST ).

I did a lot of research, response params got "new_recaptcha_token".
It's not "new_google_recaptcha_token".

```
-        params[:new_google_recaptcha_token],
+        params[:new_recaptcha_token],
```

(I'm not good at English, sorry)

**Comment by igorkasyanchuk** [comment]
try new version - new_google_recaptcha-1.4.0.gem
