### ISSUE TITLE
Captcha displays on page load

### ISSUE THREAD

**Issue by mvanio** [igorkasyanchuk/new_google_recaptcha#8]
It is possible I'm misunderstanding the instructions but the recaptcha form displays as soon as the form page loads. I have followed the config setup in the readme and `<%= recaptcha_action('contact') %>` appears in the `<form>`. My controller action is not 'create' as in the instructions but 'contact' instead. This action exists in the base controller.

I expect the recaptcha to display only after user has clicked to submit form.

**Comment by igorkasyanchuk** [comment]
is it default behavior of google recaptcha 3? try official documentation and see how it works. I didn't noticed in API documentation that you have some control on when to show recaptcha form.
